### ISSUE TITLE
The font used in screenshots

### ISSUE THREAD

**Issue by budchirp** [sam4llis/nvim-tundra#1]
Whats the font name in this screenshot?
![188616879-5de60642-2ee2-4632-8afe-18156fb7a16f](https://user-images.githubusercontent.com/80613396/189436649-70d145f8-3e5a-4a73-a692-6b92669838d3.png)

**Comment by sam4llis** [comment]
Hi. The font is [MonoLisa](https://www.monolisa.dev). Unfortunately it's a paid font (~£40), but it's a really beautiful monospace font in my opinion.

Some similar/alternative fonts are be [Cartograph CF](https://connary.com/cartograph.html) (paid, I believe) or [JetBrains Mono](https://www.jetbrains.com/lp/mono/) (free).

**Comment by budchirp** [comment]
Thanks.
