### ISSUE TITLE
feat: add support for Neogit

### ISSUE THREAD

**Issue by D00mch** [sam4llis/nvim-tundra#10]
<img width="861" alt="image" src="https://user-images.githubusercontent.com/14236531/203619304-771e0055-0589-494b-8178-627bbec54e39.png">

[Neogit](https://github.com/TimUntersberger/neogit)

**Comment by sam4llis** [comment]
Thanks for highlighting this issue :) Commit da399a4 on the `dev` branch adds support for Neogit if you want to check it out yourself. Note that you'll have to add the following line to your `setup` function to enable the new highlight groups:

```lua
require('nvim-tundra').setup({
  plugins = {
    -- ...
    neogit = true,
    -- ...
  },
})
```

New highlight groups make the `:Neogit` interface look like the following image:

<img width="2130" alt="Screenshot 2022-11-24 at 20 10 04" src="https://user-images.githubusercontent.com/43378933/203858551-98e1d0d1-984b-40b6-a5df-2e90e280c88c.png">
