### ISSUE TITLE
Update Neogit hl groups

### ISSUE THREAD

**Issue by etrnal70** [sam4llis/nvim-tundra#12]
Just a heads up, Neogit introduce several new highlight group for various components. Would be great to get this properly themed !

https://github.com/NeogitOrg/neogit/pull/630

**Comment by sam4llis** [comment]
Thanks for letting me know about this :) I've added a commit to the `dev` branch f71055c that has populated some of the new highlight groups. At the moment, it looks similar to the following:

<img width="1002" alt="image" src="https://github.com/sam4llis/nvim-tundra/assets/43378933/9533e0ca-bd02-4f08-bb8a-cd7a64d4f3b6">

I'm not too familiar with Neogit though (and don't have time to learn its intricacies!), so if you do spot anything that looks 'off' please let me know or create a PR!

If you're happy with how it looks now though I will merge into `main` and tag with `v0.4.2` :)

**Comment by etrnal70** [comment]
Cool, thanks for the changes! Will report back later after using it for work

**Comment by etrnal70** [comment]
Sorry, forgot to give a response. I think the current highlight seems good and ready to go ! I also planned to contribute some plugin support to next month. I'll open a MR if it's necessary

**Comment by sam4llis** [comment]
Great thanks for checking :) Have just merged into `main` and tagged `v0.4.2`. Thanks for any future contributions you make as well!
