### ISSUE TITLE
Not set `g:color_names`

### ISSUE THREAD

**Issue by tan-wei** [sam4llis/nvim-tundra#13]
Now `g:color_names` is not set, so after I use `tundra`, the `:colorscheme` command will simply return `default` which is not the truth.

Thanks!

**Comment by sam4llis** [comment]
Hi, thanks for flagging this :) I've just added a commit in the `dev` branch (4c93e03) - let me know if   this is okay and I'll promote to `main`!

**Comment by tan-wei** [comment]
I can confirm it is fixed after I use `dev` branch. If merged to `main`, the issue should be closed.

**Comment by sam4llis** [comment]
Great, have added to `main` 4c93e03! I'll add a tag `v0.4.3` for this fix too. Thanks for highlighting the issue :)

**Comment by tan-wei** [comment]
Thanks very much! It works well now with the latest version.
