### ISSUE TITLE
Some icons not working after activating tundra

### ISSUE THREAD

**Issue by hedyhli** [sam4llis/nvim-tundra#14]
I do apologize in advance as this is the weirdest problem I've encountered in nvim.

Somehow, when I've not activated tundra, all icons can show up properly.

After activating tundra theme, icons in buffers still show up correctly, but *some* icons no longer work in other places.

Do check out the recording below.

Again, I'm not sure how nvim-tundra could affect how icons are shown, so I have no idea how to go about troubleshooting this.

https://github.com/sam4llis/nvim-tundra/assets/50042066/ab46acb1-6db3-47f0-b429-eec860cb2f95

(if it's too blurry to discern the text do let me know)

This is not just a problem with Lazy, I've also observed that the vcs branch icon in my statusline also does not show up correctly (but does show in a file buffer).

**Comment by sam4llis** [comment]
Hi thanks for creating an issue about this :)

This is probably one of weirdest bugs I’ve seen - I’ve got no idea how tundra could be affecting specific icons within the Lazy window! I’d have to do a bit of digging into this (not sure I will have the time over the next couple of weeks though, so sorry about that).

Is it just that one icon that is changing or any others? And if you could paste that icon here for reference that would be great :)

**Comment by hedyhli** [comment]
Thanks for the quick reply!

As far as I know, these icons do not show up correctly:

```
 (vcs branch)
 (lightning symbol)
```

In the:
- statusline (tab line and win bar both work though)
- Lazy.nvim UI

I'm using Symbols Nerd Font (Mono), on nvim-0.9.4

Will update if I find more

**Comment by hedyhli** [comment]
Weird, it appears that after modifying my [kitty terminal font config](https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font), the two icons now show up correctly in nvim with tundra.

Closing since it was probably an issue with the terminal setup (but still weird that it worked with other color schemes before this!)

**Comment by sam4llis** [comment]
Apologies, missed the messages above! Glad you found the solution :) It's weird that it seemed to only be a Tundra issue - reopen this if it persists in any way!
