### ISSUE TITLE
Inlay Hints Not Showing

### ISSUE THREAD

**Issue by mickalpine** [sam4llis/nvim-tundra#15]
Neovim Version:
0.10.0: ubuntu1+git202401282104-47cd532bf-971e32c87-6850187d2~ubuntu22.04.1

The lsp inlay hints are not showing, even when changing to an overridden color (not that I want to override the color, I just want the inlay hints displayed)

My config for loading tundra with Lazy:
```lua
  {
    "sam4llis/nvim-tundra",
    opts = {
      diagnostics = {
        hints = { fg = "#FF0000", bg = "#FF0000" },
      },
    },
  },
```

Here is a screenshot of a go file using gopls lsp with all inlay hints enabled:
![image](https://github.com/sam4llis/nvim-tundra/assets/128929391/ae5d4ae2-706f-4fb4-ba67-63a16d4f4594)

Note the gap where the inlay hints should be displayed. This is with catppuccin:
![image](https://github.com/sam4llis/nvim-tundra/assets/128929391/b2f981d8-7165-449e-8a53-951737d3e766)

I love this theme so much, and use it for my terminal, thank you so much for it!

**Comment by sam4llis** [comment]
Hi! Thanks for using the theme :)

Currently I'm still on nvim-0.8, so hadn't realised inlay hints were released in 0.10... However I think you've confused the `DiagnosticInfo` highlight group (`:h hl-DiagnosticInfo`) with those related to inlay hints.

I've just added this commit (1173df4) to the `dev` branch which adds an initial implementation of the latest `LspInlayHint` highlight group (`:h hl-LspInlayHint`).

If you change your lazy configuration to barebones and use the `dev` branch version of `ivim-tundra`, I'm hoping that you'll be able to see the highlights!

```
  {
    "sam4llis/nvim-tundra",
    opts = {},
  },
```

Let me know if not and I can hopefully look into it properly at the weekend :)

**Comment by mickalpine** [comment]
That fixed it, I added the patch to my local source of the repo and it worked flawlessly. Thank you once again!

**Comment by mickalpine** [comment]
A bizarre side-effect. Now vim-illuminate throws errors after changing that line.
```lua
vim-illuminate: An internal error has occured: false"...nvim/lazy/nvim-treesitter/lua/nvim-treesitter/locals.lua:44: attempt to index field 'local' (a nil value)"
```

Here's the [line](https://github.com/nvim-treesitter/nvim-treesitter/blob/e24dab6696aa2a6682a117e241adc32c38e93d53/lua/nvim-treesitter/locals.lua#L44C1-L44C39):
```lua
for _, loc in ipairs(locals) do
    if loc["local"]["definition"] then
      table.insert(defs, loc["local"]["definition"])
    end
  end
  ```
  
  It could be coincidental, but out of your hands and not your problem :)
  
 **EDIT**:
`rm -rf ~/.cache/nvim` fixed this issue for me

**Comment by sam4llis** [comment]
That’s weird, I can’t see how those two could be related? If you still struggle with this let me know and I can try looking into it further :)


Maybe it’s due to the highlight groups [here](https://github.com/RRethy/vim-illuminate?tab=readme-ov-file#highlight-groups) (though unlikely). Could you try pinning ‘nvim-treesitter’ to a stable branch/commit and seeing if this changes anything?

**Comment by mickalpine** [comment]
> That’s weird, I can’t see how those two could be related? If you still struggle with this let me know and I can try looking into it further :)
> 
> Maybe it’s due to the highlight groups [here](https://github.com/RRethy/vim-illuminate?tab=readme-ov-file#highlight-groups) (though unlikely). Could you try pinning ‘nvim-treesitter’ to a stable branch/commit and seeing if this changes anything?

I just tested the config with a fresh isolated neovim install in docker and she's looking beautiful without errors.

![image](https://github.com/sam4llis/nvim-tundra/assets/128929391/7aa9636b-c507-4524-ba9d-ab1b164e48d3)

Have a great one cheers!
