### ISSUE TITLE
Add support for common statuslines

### ISSUE THREAD

**Issue by vihu** [sam4llis/nvim-tundra#2]
This is an excellent colorscheme!

It would be great if we could have support for some common statusline plugins like lualine and/or feline as well.

**Comment by sam4llis** [comment]
Thanks!

I don’t actually use a statusline so hadn’t considered adding it to the colorscheme until now. Would you mind linking some examples from other Neovim colorschemes that have this functionality? I’m not sure if it is simply highlight groups that need implementing or hard-coding components (e.g., gig branch, LSP diagnostics, etc.) :)

**Comment by vihu** [comment]
Here's a couple examples: 
- kanagawa: https://github.com/rebelot/kanagawa.nvim/tree/master/lua/lualine
- catppuccin: https://github.com/catppuccin/nvim/tree/main/lua/lualine/themes

**Comment by sam4llis** [comment]
Sorry for the late response - commit 14a3364 adds an initial `lualine.nvim` integration for Tundra. If you're happy with that I'll close this issue :) With regards to a feline integration, I'll probably open another issue for that is there's demand for it.
